"""Tests for the logical storage readers and collector."""

import os

from sensors2mqtt.collector.storage import lvm
from sensors2mqtt.collector.storage_lvm import collect_logical

# 4 MiB extents; pv0 has a 100-extent linear LV; a raid1 LV has 50-extent
# images (plus 1-extent metadata) on pv1 and pv2.
METADATA = """
# Generated by LVM2 version 2.03.31(2) (2025-02-27)
contents = "Text Format Volume Group"
version = 1
testvg {
	id = "VNzffe-dYkS-FyHA-VeuQ-Ba6O-eUWk-wznFKq"
	seqno = 12
	status = ["RESIZEABLE", "READ", "WRITE"]
	flags = []
	extent_size = 8192		# 4 Megabytes
	physical_volumes {
		pv0 {
			id = "aaaaaa-0000"
			device = "/dev/sdb"	# Hint only
			status = ["ALLOCATABLE"]
			pe_count = 1000
		}
		pv1 {
			id = "bbbbbb-1111"
			device = "/dev/sdc"	# Hint only
			pe_count = 1000
		}
		pv2 {
			id = "cccccc-2222"
			device = "/dev/sdd"	# Hint only
			pe_count = 1000
		}
	}
	logical_volumes {
		data {
			status = ["READ", "WRITE", "VISIBLE"]
			segment_count = 1
			segment1 {
				start_extent = 0
				extent_count = 100
				type = "striped"
				stripe_count = 1	# linear
				stripes = [
					"pv0", 0
				]
			}
		}
		mirror {
			status = ["READ", "WRITE", "VISIBLE"]
			segment1 {
				start_extent = 0
				extent_count = 50
				type = "raid1"
				raids = [
					"mirror_rmeta_0", "mirror_rimage_0",
					"mirror_rmeta_1", "mirror_rimage_1"
				]
			}
		}
		mirror_rimage_0 {
			status = ["READ", "WRITE"]
			segment1 { extent_count = 50 type = "striped" stripes = ["pv1", 1] }
		}
		mirror_rmeta_0 {
			status = ["READ", "WRITE"]
			segment1 { extent_count = 1 type = "striped" stripes = ["pv1", 0] }
		}
		mirror_rimage_1 {
			status = ["READ", "WRITE"]
			segment1 { extent_count = 50 type = "striped" stripes = ["pv2", 1] }
		}
		mirror_rmeta_1 {
			status = ["READ", "WRITE"]
			segment1 { extent_count = 1 type = "striped" stripes = ["pv2", 0] }
		}
	}
}
"""

EXT = 4 * 1024 * 1024


def test_parse_metadata():
    meta = lvm.parse_lvm_metadata(METADATA)
    assert meta["contents"] == "Text Format Volume Group"
    vg = meta["testvg"]
    assert vg["extent_size"] == 8192
    assert vg["status"] == ["RESIZEABLE", "READ", "WRITE"]
    assert vg["logical_volumes"]["mirror"]["segment1"]["raids"][1] == "mirror_rimage_0"


def test_vg_allocation():
    vg = lvm.vg_from_metadata(lvm.parse_lvm_metadata(METADATA),
                              lambda uuid: uuid != "cccccc-2222")
    assert vg.name == "testvg"
    assert vg.size_bytes == 3000 * EXT
    assert [(p.name, p.used_bytes // EXT, p.present) for p in vg.pvs] == [
        ("pv0", 100, True), ("pv1", 51, True), ("pv2", 51, False)]
    assert vg.free_bytes == (3000 - 202) * EXT
    assert vg.missing_pvs == 1
    # Only visible LVs; the raid's hidden sub-LVs are not listed
    assert [(lv.name, lv.type, lv.size_bytes // EXT) for lv in vg.lvs] == [
        ("data", "striped", 100), ("mirror", "raid1", 50)]


def test_read_vgs_skips_backups_of_absent_vgs(tmp_path):
    (tmp_path / "backup").mkdir()
    (tmp_path / "backup/testvg").write_text(METADATA)
    (tmp_path / "backup/gone").write_text(METADATA.replace("testvg", "gonevg"))
    byid = tmp_path / "by-id"
    byid.mkdir()
    assert lvm.read_vgs(str(tmp_path / "backup"), str(byid)) == []
    os.symlink("../../sdb", byid / "lvm-pv-uuid-aaaaaa-0000")
    vgs = lvm.read_vgs(str(tmp_path / "backup"), str(byid))
    assert {v.name for v in vgs} == {"testvg", "gonevg"}
    assert all(v.missing_pvs == 2 for v in vgs)


# Real `dmsetup status` lines from big-storage
DMSETUP = """\
storage--big-boot--debian: 0 8388608 raid raid1 2 AA 8388608/8388608 idle 0 0 -
storage--more-space: 0 107374182400 raid raid6_zr 6 DAAAAA 21474836480/21474836480 idle 0 0 -
storage--big-space--2: 0 1000 raid raid6_zr 9 AAAAAAAAA 500/1000 recover 0 0 -
storage--big-root--debian_rimage_0: 0 7654604800 integrity 3 7654604800 7654604800
storage--big-root--debian_rimage_1: 0 7654604800 integrity 2 7654604800 7654604800
storage--big-space--1: 0 134692913152 cache 8 2364/10240 4096 786411/786412 \
243504091 806257004 80819782 54949108 5342047 5342456 7 3 metadata2 writethrough
storage--big-pool-tpool: 0 2048 thin-pool 1 10/100 250/1000 - rw
storage--big-home: 0 2048 linear
"""


def test_parse_dmsetup_status():
    dm = lvm.parse_dmsetup_status(DMSETUP)
    assert dm.raid["storage-more/space"] == {
        "type": "raid6_zr", "health": "DAAAAA", "sync_pct": 100.0, "action": "idle",
        "mismatches": 0}
    assert dm.raid["storage-big/space-2"]["sync_pct"] == 50.0
    assert dm.integrity == {"storage-big/root-debian": 5}
    c = dm.cache["storage-big/space-1"]
    assert c["dirty"] == 7 and 99.9 < c["used_pct"] <= 100
    assert dm.thin_pool["storage-big/pool-tpool"] == {"metadata_pct": 10.0, "data_pct": 25.0}


def test_filesystems_and_fstab(tmp_path):
    (tmp_path / "proc/self").mkdir(parents=True)
    (tmp_path / "proc/self/mountinfo").write_text(
        "22 1 253:1 / / rw,relatime shared:1 - ext4 /dev/mapper/root rw\n"
        "23 22 253:1 /srv /bind rw - ext4 /dev/mapper/root rw\n"
        "24 22 253:2 / /space\\040ml ro,relatime - xfs /dev/mapper/ml ro\n"
        "25 22 0:20 / /run rw - tmpfs tmpfs rw\n")

    class St:
        f_frsize, f_blocks, f_bfree, f_bavail, f_files, f_ffree = 4096, 1000, 100, 50, 10, 5

    fss = lvm.read_filesystems(str(tmp_path), statvfs=lambda m: St)
    assert [(f.mountpoint, f.fstype, f.readonly) for f in fss] == [
        ("/", "ext4", False), ("/space ml", "xfs", True)]
    assert fss[0].used_pct == round(100 * 900 / 950, 1)
    fstab = "UUID=x / ext4 defaults 0 1\nUUID=y /backups ext4 defaults 0 2\n" \
            "UUID=z /mnt/usb ext4 noauto 0 0\n/swap none swap sw 0 0\n"
    assert lvm.fstab_not_mounted(fstab, {"/", "/space ml"}) == ["/backups"]


def test_collect_logical_rollups():
    vg = lvm.vg_from_metadata(lvm.parse_lvm_metadata(METADATA),
                              lambda uuid: uuid != "cccccc-2222")
    fs = lvm.Filesystem("/space-ml", "/dev/x", "ext4", False, 100, 99, 1, 1.0)
    md = lvm.MdArray("md125", "raid6", "active", 9, 1, "recover", 12.5, 0, 1000)
    out = dict((s.suffix, v) for s, v in collect_logical(
        [fs], ["/backups"], [md], [vg], lvm.parse_dmsetup_status(DMSETUP)))
    assert out["fs_space_ml_used_pct"] == 99.0
    assert out["fs_full_count"] == 1
    assert out["fs_not_mounted"] == "/backups"
    assert out["md_degraded_count"] == 1
    assert out["vg_testvg_missing_pvs"] == 1 and out["lvm_missing_pvs"] == 1
    assert out["raid_storage_more_space_failed_images"] == 1
    assert out["lvm_degraded_raids"] == 1
    assert out["lvm_resyncing_raids"] == 1
    assert out["integrity_mismatches"] == 5


def test_names_starting_with_digits():
    meta = lvm.parse_lvm_metadata('vg { 1data { extent_count = 5 } 4k-test = "x" n = -3 }')
    assert meta == {"vg": {"1data": {"extent_count": 5}, "4k-test": "x", "n": -3}}


def test_resyncing_raid_is_not_degraded():
    dm = lvm.parse_dmsetup_status("vg-new: 0 1000 raid raid1 2 aa 100/1000 resync 0 0 -\n")
    out = dict((s.suffix, v) for s, v in collect_logical([], [], [], [], dm))
    assert out["raid_vg_new_failed_images"] == 0
    assert out["raid_vg_new_unsynced_images"] == 2
    assert out["lvm_degraded_raids"] == 0 and out["lvm_resyncing_raids"] == 1


def test_btrfs_subvolumes_and_fstab_against_all_mounts(tmp_path):
    (tmp_path / "proc/self").mkdir(parents=True)
    (tmp_path / "proc/self/mountinfo").write_text(
        "22 1 0:30 /@ / rw - btrfs /dev/sda2 rw,subvol=/@\n"
        "23 22 0:30 /@home /home rw - btrfs /dev/sda2 rw,subvol=/@home\n"
        "24 22 8:3 / /data rw - ext4 /dev/sda3 rw\n"
        "25 22 8:3 /x /data2 rw - ext4 /dev/sda3 rw\n")

    class St:
        f_frsize, f_blocks, f_bfree, f_bavail, f_files, f_ffree = 4096, 10, 5, 5, 0, 0

    fss = lvm.read_filesystems(str(tmp_path), statvfs=lambda m: St)
    assert [f.mountpoint for f in fss] == ["/", "/home", "/data"]
    fstab = ("UUID=a / btrfs subvol=@ 0 0\nUUID=a /home btrfs subvol=@home 0 0\n"
             "UUID=b /data2 ext4 defaults 0 2\n")
    assert lvm.fstab_not_mounted(fstab, lvm.all_mountpoints(str(tmp_path))) == []


def test_idle_md_is_fully_synced(tmp_path):
    md = tmp_path / "sys/block/md0/md"
    md.mkdir(parents=True)
    for f, v in (("level", "raid1"), ("array_state", "clean"), ("raid_disks", "2"),
                 ("degraded", "0"), ("sync_action", "idle"), ("sync_completed", "none"),
                 ("mismatch_cnt", "0")):
        (md / f).write_text(v + "\n")
    (tmp_path / "sys/block/md0/size").write_text("2048\n")
    (a,) = lvm.read_md_arrays(str(tmp_path))
    assert (a.sync_pct, a.degraded, a.size_bytes) == (100.0, 0, 2048 * 512)


def test_lv_tree_down_to_pvs():
    devices = {"aaaaaa-0000": "sdb", "bbbbbb-1111": "sdc1"}
    vg = lvm.vg_from_metadata(lvm.parse_lvm_metadata(METADATA),
                              lambda uuid: uuid != "cccccc-2222", devices.get)
    mirror = {lv.name: lv for lv in vg.lvs}["mirror"]
    t = mirror.tree
    assert (t["name"], t["type"], t["role"]) == ("mirror", "raid1", None)
    assert [(c["name"], c["role"]) for c in t["children"]] == [
        ("mirror_rmeta_0", "rmeta"), ("mirror_rimage_0", "rimage"),
        ("mirror_rmeta_1", "rmeta"), ("mirror_rimage_1", "rimage")]
    leaf = t["children"][1]["children"][0]
    assert (leaf["pv"], leaf["device"], leaf["present"]) == ("pv1", "sdc1", True)
    # Each PV once, with the space the LV has on it (image + metadata)
    assert [(p["pv"], p["device"], p["present"], p["gb"]) for p in mirror.pvs()] == [
        ("pv1", "sdc1", True, round(51 * EXT / lvm.GB, 3)),
        ("pv2", None, False, round(51 * EXT / lvm.GB, 3))]


def test_thin_lv_tree_reaches_the_pool_pvs():
    meta = lvm.parse_lvm_metadata('''vg { extent_size = 8192
      physical_volumes { pv0 { id = "u0" pe_count = 100 } }
      logical_volumes {
        thin1 { status = ["VISIBLE"] segment1 { extent_count = 50 type = "thin"
                thin_pool = "pool" transaction_id = 1 device_id = 1 } }
        pool { status = ["VISIBLE"] segment1 { extent_count = 10 type = "thin-pool"
               metadata = "pool_tmeta" pool = "pool_tdata" } }
        pool_tdata { segment1 { extent_count = 10 type = "striped" stripes = ["pv0", 0] } }
        pool_tmeta { segment1 { extent_count = 1 type = "striped" stripes = ["pv0", 10] } }
      } }''')
    vg = lvm.vg_from_metadata(meta, lambda u: True, lambda u: "sdb")
    thin = {lv.name: lv for lv in vg.lvs}["thin1"]
    assert [c["name"] for c in thin.tree["children"]] == ["pool"]
    assert [(p["pv"], p["device"]) for p in thin.pvs()] == [("pv0", "sdb")]


def test_filesystem_backing_chain():
    devices = {"aaaaaa-0000": "sdb", "bbbbbb-1111": "sdc1"}
    vg = lvm.vg_from_metadata(lvm.parse_lvm_metadata(METADATA),
                              lambda uuid: uuid != "cccccc-2222", devices.get)
    disks = {"sdc1": [{"dev": "sdc", "serial": "SERC", "model": "M"}],
             "sdb": [{"dev": "sdb", "serial": "SERB", "model": "M"}],
             "nvme0n1p1": [{"dev": "nvme0n1", "serial": "SERN", "model": "N"}]}
    on_lv = lvm.Filesystem("/data", "/dev/mapper/testvg-mirror", "ext4", False, 1, 1, 1, 1.0)
    plain = lvm.Filesystem("/boot/efi", "/dev/nvme0n1p1", "vfat", False, 1, 1, 1, 1.0)
    backing = {"/data": ("testvg/mirror", None), "/boot/efi": (None, "nvme0n1p1")}
    out = dict((s.suffix, v) for s, v in collect_logical(
        [on_lv, plain], [], [], [vg], lvm.DmStatus(),
        lambda dev: disks.get(dev, []), lambda fs: backing[fs.mountpoint]))
    assert (out["fs_data_lv"], out["fs_data_vg"]) == ("testvg/mirror", "testvg")
    assert out["fs_data_pvs"].state == "sdc1, missing pv2"
    assert [p["disks"] for p in out["fs_data_pvs"].attributes["pvs"]] == [disks["sdc1"], []]
    assert out["fs_data_drives"].state == "SERC"
    assert (out["fs_boot_efi_lv"], out["fs_boot_efi_pvs"].state) == ("none", "none")
    assert out["fs_boot_efi_drives"].attributes == {"drives": disks["nvme0n1p1"]}
    # The VG lists its PVs; each PV names its device and drive
    assert out["vg_testvg_pv_list"].state == "sdb, sdc1, missing pv2"
    pv2 = out["vg_testvg_pv_list"].attributes["pvs"][2]
    assert (pv2["pv"], pv2["present"], pv2["last_seen_as"]) == ("pv2", False, "/dev/sdd")
    assert out["pv_testvg_aaaaaa_0000_device"] == "sdb"
    assert out["pv_testvg_aaaaaa_0000_drive"] == "SERB"
    assert out["pv_testvg_cccccc_2222_device"] == "missing"
    layout = out["lv_testvg_mirror_layout"]
    assert layout.state == "raid1 on 2 PVs (1 missing)"
    assert layout.attributes["tree"]["children"][1]["children"][0]["disks"] == disks["sdc1"]


def test_short_list_fits_a_state():
    from sensors2mqtt.collector.storage_lvm import short_list
    assert short_list([]) == "none"
    assert short_list(["a", "b"]) == "a, b"
    long = [f"SERIAL{i:04d}XXXXXXXXXX" for i in range(20)]
    s = short_list(long)
    assert len(s) <= 255 and s.endswith(f"(+{20 - s.count('SERIAL')})")
